<a href="https://colab.research.google.com/github/DianaIbar/Seccion7/blob/main/Laboratio7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#-	Crear un DataFrame con los nombres, profesión y países de 8 personas, y luego imprimir el DataFrame
import pandas as pd

datos = {'nombre': ['Diana', 'Daniela', 'Angel', 'Daniel', 'Walter', 'Darling', 'Julian', 'Manuel'],
         'Profesion': ['Contador', 'Medico', 'Abogado', 'Docente', 'Astronauta', 'Periodista', 'Bacteriologo', 'Psiquiatra'],
         'Paises': ['Colombia', 'Ecuador', 'Chile', 'Jamaica', 'Honduras', 'Suecia', 'España','Portugal']}


df = pd.DataFrame(datos)
print(df)



    nombre     Profesion    Paises
0    Diana      Contador  Colombia
1  Daniela        Medico   Ecuador
2    Angel       Abogado     Chile
3   Daniel       Docente   Jamaica
4   Walter    Astronauta  Honduras
5  Darling    Periodista    Suecia
6   Julian  Bacteriologo    España
7   Manuel    Psiquiatra  Portugal


In [18]:
#-	Cargar un archivo CSV (puedes usar un archivo de ejemplo en tu entorno) y mostrar las primeras 5 filas.

import pandas as pd
df = pd.read_csv('data.csv')
print(df.head(5))

   Duracion  Pulso  Maxpulso  Calorias
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [23]:
#-Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios, y luego mostrar un resumen estadístico de los datos.
import numpy as np
import pandas as pd
#generar DataFrame con valores aleatorios
df = pd.DataFrame(np.random.rand(100, 8))
#mostrar resumen estadistico
print(df.describe())

                0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.480777    0.486547    0.480088    0.483910    0.478296    0.475627   
std      0.292495    0.287897    0.291020    0.272318    0.301685    0.294903   
min      0.001030    0.001112    0.003319    0.015995    0.001837    0.014298   
25%      0.232769    0.208928    0.225567    0.270342    0.194382    0.189207   
50%      0.448324    0.498751    0.451479    0.445581    0.465830    0.482572   
75%      0.763612    0.733115    0.724283    0.713757    0.700575    0.738008   
max      0.994566    0.970160    0.991805    0.944272    0.987980    0.996656   

                6           7  
count  100.000000  100.000000  
mean     0.473495    0.471616  
std      0.279944    0.288093  
min      0.005433    0.007417  
25%      0.207537    0.246186  
50%      0.446501    0.428440  
75%      0.661029    0.715766  
max      0.992

In [32]:
#-	Crear un array de números del 1 al 10 y mostrar la suma, la media, y el valor máximo.
import numpy as np
arr = np.arange(1, 11)
print("Array:",arr)
print("Suma:", arr.sum())
print("Media:",arr.mean())
print("Máximo:",arr.max())


Array: [ 1  2  3  4  5  6  7  8  9 10]
Suma: 55
Media: 5.5
Máximo: 10


In [33]:
#Crear un array de 3x4 lleno de ceros y luego cambiar su forma a 2x6
import numpy as np
arr = np.zeros((3,4))
print(arr)
arr = arr.reshape(2,6)
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [34]:
#Generar una matriz aleatoria de 3x3 y calcular su transpuesta.
import numpy as np
arr = np.random.rand(3,3)
print(arr)
print(arr.T)

[[0.13406108 0.09733047 0.57740899]
 [0.17200345 0.37379175 0.17903723]
 [0.30309836 0.91796567 0.06944132]]
[[0.13406108 0.17200345 0.30309836]
 [0.09733047 0.37379175 0.91796567]
 [0.57740899 0.17903723 0.06944132]]


In [38]:
#Concatenar dos arrays de NumPy, cada uno con 5 valores, y luego imprimir el array concatenado
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr3 = np.concatenate((arr1,arr2))

import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
arr_concatenado = np.concatenate((a,b))
print("Array concatenado:",arr_concatenado)

Array concatenado: [ 1  2  3  4  5  6  7  8  9 10]
